name: "Pull Request Labeler"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
